# Site settings
title: Cyril Macé
slogan : Contes et Chansons
email: bonjour@cyrilconte.com
sass:
    load_paths:
        - css
collections:
  projets :
    name: true
    desc: true
    duree: true
    public: true
    output: true
    extrait : true
  dates :
    name: true
    desc: true
    duree: true
    public: true
    output: true
  chansons :
    name: true
    desc: true
    duree: true
  medias :
months:
    - Janvier
    - Février
    - Mars
    - Avril
    - Mai
    - Juin
    - Juillet
    - Aout
    - Septembre
    - Octobre
    - Novembre
    - Décembre

plugins:
  - jekyll-admin
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"